# -*- coding: utf-8 -*-
"""Merge tools/out/item_details.json into EmberLoot/data.lua (EL_Items rows gain a 5th field).

Parses each EL_Items row with a small state-machine (escaped quotes safe),
appends the compact detail table literal when the id exists in the crawl output.
Idempotent: rows already having 5+ fields are rebuilt from scratch.
"""
import json, re, sys, io

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

DATA = r'D:\workspace\emberloot\EmberLoot\data.lua'
DETAILS = r'D:\workspace\emberloot\tools\out\item_details.json'

KEY_ORDER = ['il', 'rl', 'c', 'sc', 'inv', 'b', 'mc', 'ar', 'bl', 'dl', 'du', 'bp', 'sp', 're',
             'st', 'rs', 'dg', 'spx', 'dx_en', 'dx_zh', 'set_id', 'set_en', 'set_zh']

def esc(s):
    return ('' + s).replace('\\', '\\\\').replace('"', '\\"').replace('\r', '\\r').replace('\n', '\\n')

def lua_val(v):
    if isinstance(v, bool):
        return 'true' if v else 'false'
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return '"' + esc(v) + '"'
    if isinstance(v, list):
        return '{' + ','.join(lua_val(x) for x in v) + '}'
    raise TypeError(repr(type(v)))

def lua_detail(det):
    parts = []
    for k in KEY_ORDER:
        if k in det and det[k] is not None:
            parts.append(k + '=' + lua_val(det[k]))
    return '{' + ','.join(parts) + '}'

def parse_row_body(body):
    """Split '{a,b,c,...}' at top level commas; return python list of lua values (strings/numbers)."""
    assert body.startswith('{') and body.endswith('}')
    inner = body[1:-1]
    fields, cur, depth, instr, escn = [], '', 0, False, False
    for ch in inner:
        if escn:
            cur += ch
            escn = False
            continue
        if instr:
            if ch == '\\':
                cur += ch
                escn = True
            elif ch == '"':
                instr = False
                cur += ch
            else:
                cur += ch
            continue
        if ch == '"':
            instr = True
            cur += ch
        elif ch == '{':
            depth += 1
            cur += ch
        elif ch == '}':
            depth -= 1
            cur += ch
        elif ch == ',' and depth == 0:
            fields.append(cur.strip())
            cur = ''
        else:
            cur += ch
    if cur.strip():
        fields.append(cur.strip())
    out = []
    for f in fields:
        if f.startswith('"') and f.endswith('"'):
            out.append(f[1:-1].replace('\\"', '"').replace('\\\\', '\\'))
        else:
            out.append(f)
    return out

def unescape(s):
    return s.replace('\\"', '"').replace('\\\\', '\\').replace('\\r', '\r').replace('\\n', '\n')

def main():
    details = json.load(open(DETAILS, encoding='utf-8'))
    print('details:', len(details))
    lines = open(DATA, encoding='utf-8').read().split('\n')
    out, in_items, n_upd, n_items = [], False, 0, 0
    row_re = re.compile(r'^\s*\[(\d+)\] = (\{.*\}),?\s*$')
    for ln in lines:
        if ln.startswith('EL_Items = {'):
            in_items = True
            out.append(ln)
            continue
        if in_items and ln.strip() == '}':
            in_items = False
            out.append(ln)
            continue
        if in_items:
            m = row_re.match(ln)
            if m:
                iid = int(m.group(1))
                fields = parse_row_body(m.group(2))
                n_items += 1
                if len(fields) >= 4 and str(iid) in details:
                    det = details[str(iid)]
                    if det:
                        name_en = unescape(fields[0]) if fields[0].startswith('"') else fields[0]
                        name_en = fields[0]
                        row = '  [%d] = {"%s","%s",%s,"%s",%s},' % (
                            iid, fields[0], fields[1], fields[2], fields[3], lua_detail(det))
                        out.append(row)
                        n_upd += 1
                        continue
            out.append(ln)
            continue
        out.append(ln)
    # header note
    for i, ln in enumerate(out):
        if ln.startswith('-- EmberLoot data'):
            out[i] = '-- EmberLoot data v2 (generated by tools/crawl.py + tools/crawl_items.py + tools/gen_data_v2.py - do not edit)'
            break
    open(DATA, 'w', encoding='utf-8', newline='\n').write('\n'.join(out))
    print('item rows seen:', n_items, 'updated with details:', n_upd)

if __name__ == '__main__':
    main()
